"""Tests for KAT Bulgaria."""

from kat_bulgaria.data_models import PersonalIdentificationType

from custom_components.kat_bulgaria.const import (
    CONF_BULSTAT,
    CONF_DOCUMENT_NUMBER,
    CONF_DOCUMENT_TYPE,
    CONF_DRIVING_LICENSE,
    CONF_PERSON_EGN,
    CONF_PERSON_NAME,
    CONF_PERSON_TYPE,
    PersonType,
)

EGN_VALID = "0011223344"
LICENSE_VALID = "123456789"
GOV_ID_VALID = "AA1234567"
BULSTAT_VALID = "000000000"
CAR_PLATE_VALID = "OB4444AP"

EGN_INVALID = "9988776655"
LICENSE_INVALID = "123"
GOV_ID_INVALID = "999"
BULSTAT_INVALID = "321"
CAR_PLATE_INVALID = "фф 1234 шш"

MOCK_ENTRY_TITLE = "KAT - test"
MOCK_USER_NAME = "test"

PATCH_VALIDATE_CREDS_INDIVIDUAL = (
    "kat_bulgaria.kat_api_client.KatApiClient.get_obligations_individual"
)
PATCH_VALIDATE_CREDS_BUSINESS = (
    "kat_bulgaria.kat_api_client.KatApiClient.get_obligations_business"
)

MOCK_DATA_INDIVIDUAL = {
    CONF_PERSON_NAME: MOCK_USER_NAME,
    CONF_PERSON_EGN: EGN_VALID,
    CONF_DOCUMENT_NUMBER: LICENSE_VALID,
    CONF_DOCUMENT_TYPE: PersonalIdentificationType.DRIVING_LICENSE,
}

MOCK_DATA_INDIVIDUAL_FULL = {
    CONF_PERSON_TYPE: PersonType.INDIVIDUAL,
    **MOCK_DATA_INDIVIDUAL,
}

MOCK_DATA_INDIVIDUAL_CAR_PLATE = {
    CONF_PERSON_NAME: MOCK_USER_NAME,
    CONF_PERSON_EGN: EGN_VALID,
    CONF_DOCUMENT_NUMBER: CAR_PLATE_VALID,
    CONF_DOCUMENT_TYPE: PersonalIdentificationType.CAR_PLATE_NUM,
}

MOCK_DATA_INDIVIDUAL_CAR_PLATE_FULL = {
    CONF_PERSON_TYPE: PersonType.INDIVIDUAL,
    **MOCK_DATA_INDIVIDUAL_CAR_PLATE,
}

MOCK_DATA_BUSINESS = {
    CONF_PERSON_NAME: MOCK_USER_NAME,
    CONF_PERSON_EGN: EGN_VALID,
    CONF_DOCUMENT_NUMBER: GOV_ID_VALID,
    CONF_BULSTAT: BULSTAT_VALID,
}

MOCK_DATA_BUSINESS_FULL = {
    CONF_PERSON_TYPE: PersonType.BUSINESS,
    **MOCK_DATA_BUSINESS,
}

MOCK_DATA_V1 = {
    CONF_PERSON_NAME: MOCK_USER_NAME,
    CONF_PERSON_EGN: EGN_VALID,
    CONF_DRIVING_LICENSE: LICENSE_VALID,
}
