"""Constants for tests."""

from custom_components.kat_bulgaria.const import CONF_PERSON_NAME, CONF_PERSON_EGN, CONF_DRIVING_LICENSE


TEST_PERSON_NAME = "Nikola"
TEST_PERSON_EGN = "0011223344"
TEST_PERSON_LICENSE = "123456789"

TEST_CONFIG = {
    CONF_PERSON_NAME: TEST_PERSON_NAME,
    CONF_PERSON_EGN: TEST_PERSON_EGN,
    CONF_DRIVING_LICENSE: TEST_PERSON_LICENSE
}